### ISSUE TITLE
Braavos address fails the validateChecksumAddress

### ISSUE THREAD

**Issue by schwepps** [starknet-io/starknet.js#1031]
**Describe the bug**
When I want to validate a Braavos address with the validateChecksumAddress function, it returns false.

**To Reproduce**
Copy and paste a Braavos address and use validateChecksumAddress(address)

**Expected behavior**
It returns true

**Screenshots**
n/a

**Desktop (please complete the following information):**

- Browser & version: Chrome
- Node version: 18.0.0
- Starknet.js version: 5.24.3
- Network: mainnet

**Additional context**
It's working with Argent address when you copy paste from wallet.
It's not working with Braavos because the address is full lowercase and to not pass the getChecksumAddress validation.

**Comment by ivpavici** [comment]
checking!

**Comment by ivpavici** [comment]
From Ethers docs:
**If the case is mixed, it is a Checksum Address**, which uses a specific pattern of uppercase and lowercase letters within a given address to reduce the risk of errors introduced from typing an address or cut and paste issues.

So from this definition I conclude that `validateChecksumAddress` is doing it's job, since all lowercase addresses are not checksum addresses...

cc @janek26 @yoga-braavos

**Comment by schwepps** [comment]
Thanks @ivpavici. 
I also think that the best solution is for Braavos to paste the address with the correct pattern when copied from the wallet.
I sent them the expected pattern.

**Comment by tabaktoni** [comment]
Correct behavior resolved
