### ISSUE TITLE
Check out Viem project

### ISSUE THREAD

**Issue by ivpavici** [starknet-io/starknet.js#653]
https://viem.sh/

What can we take for inspiration? 

"An alternative to ethers.js and web3.js with a focus on reliability, efficiency, and excellent developer experience."

**Comment by dhruvkelawala** [comment]
https://github.com/wagmi-dev/viem/blob/main/src/actions/public/readContract.ts

**Comment by tabaktoni** [comment]
I do not see any specific code magic from Viem that is "reliability, efficiency, and excellent developer experience"?
Can you do a comparison table for exact features?

**Comment by jxom** [comment]
@tabaktoni 

**Reliability**
- 100% test coverage (+ many many behavioral test cases that do not cover branch testing)
- Our test suite runs against a forked Ethereum node 
- Our APIs are fully typed, and rely in inferrence as much as possible

**Efficiency**
- All of our coding algorithms (ABI, RLP, etc) are around ~3-8x faster than ethers
- We only perform async tasks when required (no unnessessary `eth_chainId` or `eth_estimateGas` requests)
- Bundle size is ~3x smaller, and modules are designed to be tree-shaken

**Developer Experience**
- Pure, deterministic, and stateless APIs with no "blackboxing"/side-effects
- Statically Typed ABIs (no need for a typechain build step)
- Chain as the souce of truth, instead of the overhead of plugins (for chain formatting, serializers, fee data, etc)

These are the points that come to my mind instantly, but there are a lot lot more.

https://viem.sh/docs/introduction.html

**Comment by ivpavici** [comment]
From a discussion on Slack:

_how do you feel about an option in the RpcProvider to automatically batch rpc calls made in the same loop of the event loop (or within a time period) together? That's what viem does and it helps avoid 429 errors. Implementation (by copying viem code, so licensing/attribution requires consideration) is trivial to add https://gist.github.com/fracek/29909e0a7cff91861959d34ad2bf3a0e_

_This one is about using json-rpc batch requests (basically sending an array of requests instead of many single requests). It can be be optin by setting batch to false by default._

https://viem.sh/docs/clients/transports/http.html#batch-optional

cc @fracek

**Comment by WiseMrMusa** [comment]
@jxom I tried reaching out to you on twitter. I am a big fan of your work with the Wagmi EVM Team and would love a conversation with you
