### ISSUE TITLE
call contract failed

### ISSUE THREAD

**Issue by mingjingc** [starknet-io/starknet.js#975]
<img width="577" alt="image" src="https://github.com/starknet-io/starknet.js/assets/17808422/dfcb76d1-4a8e-4204-958e-ee27fcb2742a">

Why contract_address is my account, not ERC20 smart contract address?

**Comment by penovicp** [comment]
You should familiarize yourself with how the Starknet network works: [Starknet docs](https://docs.starknet.io/documentation/).

in short, accounts are the main interface through which users interact with the network, because of this they have various security measures one of which is replay protection that relies on the nonce values tied to accounts. You bound your account for interacting with the contract on line 21 of the screenshot.

If you have more questions after going through the documentation, the [Starknet Discord](https://discord.gg/qypnmzkhbc) is the better place to ask.
